trigger:
- main

pool:
  vmImage: 'vs2017-win2016'

variables:
  - group: ADO-TF-AWS-VPC-Int
  - name: region
    value: 'us-east-1'

steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: 'Install Terraform 0.13.5'
  inputs:
    terraformVersion: 0.13.5

- powershell: |
   Write-Host "This is the current working directory: $(build.sourcesdirectory)"
   terraform init -backend-config="bucket=skundu-terraform-remote-state" -backend-config="key=tf/ADO-TF-VPC-Int/terraform.tfstate" -backend-config="region=$(region)" -backend-config="access_key=$(access_key)" -backend-config="secret_key=$(secret_key)" -no-color
  workingDirectory: $(build.sourcesdirectory)
  displayName: 'terraform init'

- powershell: |
   'terraform validate -json'
  workingDirectory: $(build.sourcesdirectory)
  displayName: 'terraform validate'